### ISSUE TITLE
System crashes instantly when training

### ISSUE THREAD

**Issue by ryanstull** [Lasagne/Lasagne#667] opened 2016-04-24 04:06 UTC
When I type "python mnist.py mlp 5"  my system crashes when it gets to the training part.

I'm running Ubuntu 15.10, linux kernel: 4.2.0-35-generic

**Comment by alexjc** [comment] 2016-04-24 07:02
It's likely you'll need a better bug report if you expect any useful help! Callstack, error message.

**Comment by f0k** [comment] 2016-04-24 12:19
Most probably this is a Theano bug. Can you please [update Lasagne and Theano to the bleeding-edge version](http://lasagne.readthedocs.org/en/latest/user/installation.html#bleeding-edge-version) and try again? What exactly is the output? (If it's extremely large, just post the last 20-30 lines.)

**Comment by gobrewers14** [comment] 2016-04-24 15:32
I think I've ran into this problem before.  Ubuntu 15 ships with gcc v5.2+.  Theano will complain about anything greater than 4.9.

**Comment by ryanstull** [comment] 2016-04-24 17:29
@alexjc I get an instant Black screen of death.  
Here's more system info:
Processor		: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Memory		: 16274MB (1656MB used)
Operating System		: Ubuntu 15.10
User Name		: ryan (ryan)
Date/Time		: Sun 24 Apr 2016 01:28:16 PM EDT
-Display-
Resolution		: 1920x1080 pixels
OpenGL Renderer		: GeForce GTX 970/PCIe/SSE2
X11 Vendor		: The X.Org Foundation

@f0k I tried upgrading to the lastest version but it didn't seem to help, same result

Here's what I see before the system crashes

$ mnist.py mlp 5
Loading data...
Downloading train-images-idx3-ubyte.gz
Downloading train-labels-idx1-ubyte.gz
Downloading t10k-images-idx3-ubyte.gz
Downloading t10k-labels-idx1-ubyte.gz
Building model and compiling functions...
Starting training...

Then it instantly reboots

**Comment by f0k** [comment] 2016-04-24 20:52
> Then it instantly reboots

Crazy. That shouldn't be possible for a Theano bug.

It looks like you're not even running on GPU, is that true? If it was running on GPU, maybe your card is broken, or the driver, and I'd suggest to try a more recent (or older) version of the nvidia driver. If it's running on CPU, maybe your RAM is broken? Can you run memtest86 for 2-3 hours? It should be in the boot menu for Ubuntu.

**Comment by nouiz** [comment] 2016-04-29 19:21
If it reboot alone, this can be caused by a low quality PSU or an under
powerful PSU. This happened to us with some "certified" workstations...

**Comment by f0k** [comment] 2016-05-11 09:33
Closing because it cannot be caused by Lasagne. Would still be curious to hear what it was when you found out!

**Closed by f0k** 2016-05-11 09:33 UTC
