### ISSUE TITLE
lasagne\layers\base.py

### ISSUE THREAD

**Issue by lyf102030** [Lasagne/Lasagne#917] opened 2019-05-07 07:33 UTC
I tried to run a model on python3.7 but ran the code with the following error:
```
TypeError Traceback (most recent call last)
in 
11 if tutor_name.startswith('RL'):
12 agent = build_tutor(n_items)
---> 13 R[k, i, :, j] = agent.train(rl_env, n_eps=n_eps)
14 else:
15 if 'Thresh' in tutor_name:
in train(self, gym_env, n_eps)
9 policy = CategoricalGRUPolicy(
10 env_spec=env.spec, hidden_dim=32,
---> 11 state_include_action=False)
12 self.raw_policy = LoggedTRPO(
13 env=env,
E:\Anaconda\lib\site-packages\rllab\policies\categorical_gru_policy.py in init(self, env_spec, hidden_dim, feature_network, state_include_action, hidden_nonlinearity)
72 hidden_nonlinearity=hidden_nonlinearity,
73 output_nonlinearity=TT.nnet.softmax,
---> 74 name="prob_network"
75 )
76
E:\Anaconda\lib\site-packages\rllab\core\network.py in init(self, input_shape, output_dim, hidden_dim, hidden_nonlinearity, output_nonlinearity, name, input_var, input_layer)
226 nonlinearity=output_nonlinearity,
227 W=l_output_flat.W,
--> 228 b=l_output_flat.b,
229 )
230
E:\Anaconda\lib\site-packages\lasagne\layers\dense.py in init(self, incoming, num_units, W, b, nonlinearity, **kwargs)
62 b=init.Constant(0.), nonlinearity=nonlinearities.rectify,
63 **kwargs):
---> 64 super(DenseLayer, self).init(incoming, **kwargs)
65 self.nonlinearity = (nonlinearities.identity if nonlinearity is None
66 else nonlinearity)
E:\Anaconda\lib\site-packages\lasagne\layers\base.py in init(self, incoming, name)
42 self.params = OrderedDict()
43
---> 44 if any(d is not None and d <= 0 for d in self.input_shape):
45 raise ValueError((
46 "Cannot create Layer with a non-positive input_shape "：
E:\Anaconda\lib\site-packages\lasagne\layers\base.py in (.0)
42 self.params = OrderedDict()
43
---> 44 if any(d is not None and d <= 0 for d in self.input_shape):
45 raise ValueError((
46 "Cannot create Layer with a non-positive input_shape "
TypeError: '<=' not supported between instances of 'tuple' and 'int'
```
How to solve this problem?
Thanks!

**Comment by f0k** [comment] 2019-05-22 12:59
The line `if any(d is not None and d <= 0 for d in self.input_shape):` is meant to iterate over the dimensions of your input shape and ensure they are either `None` (= unknown) or positive. The error says it cannot compare a `tuple` to an `int`, so `d <= 0` was evaluated with `d` being a `tuple`. This means your input shape contains tuples.
You should check how the `InputLayer` of your network is defined, maybe it was set to have a tuple of tuples as its shape.
If you run your script with `python -m pdb thescript.py` (and then enter `c` for `continue`), it will give you a pdb prompt at the exception, so you can investigate and do `print self.input_shape`.

Hope this helps! Closing as it's very likely not a bug in Lasagne, but in user code. Please still feel free to continue discussing here.

**Closed by f0k** 2019-05-22 12:59 UTC
