### ISSUE TITLE
lasagne.layers.get_output( l_emb ) for an EmbeddingLayer using theano.function( [l_in.input_var], output) raises error

### ISSUE THREAD

**Issue by mt311** [Lasagne/Lasagne#481] opened 2015-11-06 17:19 UTC
Using l_in.input_var as the input to theano.function() for an EmbeddingLayer per this simple example:

```
import numpy as np
import theano
import lasagne

VOCABULARY_SIZE = 5 
EMBEDDING_SIZE = 10
N_BATCH = 10
MAX_LENGTH = 3 
 
# Prepare data
x_train_set = np.asarray( [[1, 2, 4] for i in xrange(20)], dtype='int32' ) 

# Layers
l_in = lasagne.layers.InputLayer( (N_BATCH, MAX_LENGTH) ) 

l_emb = lasagne.layers.EmbeddingLayer(
  l_in,
  input_size=VOCABULARY_SIZE,
  output_size=EMBEDDING_SIZE,
  W=lasagne.init.Uniform(0.1)
) 

# Output
output = lasagne.layers.get_output( l_emb ) 

# Function
train = theano.function( [l_in.input_var], output ) 

# Train
train_output = train(
  x_train_set[0: N_BATCH],
) 

print 'train_output.shape: ', train_output.shape
print 'train_output: ', train_output
```

Results in the following error:

Traceback (most recent call last):
  File "embed.py", line 28, in <module>
    output = lasagne.layers.get_output( l_emb )
  File "/usr/local/src/Lasagne/lasagne/layers/helper.py", line 185, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/usr/local/src/Lasagne/lasagne/layers/embedding.py", line 69, in get_output_for
    return self.W[input]
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/var.py", line 474, in __getitem__
    return self.take(args[axis], axis)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/var.py", line 506, in take
    return theano.tensor.subtensor.take(self, indices, axis, mode)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 2290, in take
    return take(a, indices.flatten(), axis, mode).reshape(shape, ndim)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 2268, in take
    return advanced_subtensor1(a, indices)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 509, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 1608, in make_node
    raise TypeError('index must be integers')
TypeError: index must be integers

However, switching get_output() to take (l_emb, x) executes properly:

```
import numpy as np
import theano
import theano.tensor as T
import lasagne

VOCABULARY_SIZE = 5
EMBEDDING_SIZE = 10
N_BATCH = 5
MAX_LENGTH = 3

x = T.imatrix( 'inputs' )
x.reshape( (N_BATCH, MAX_LENGTH) )

# Prepare data
x_train_set = np.asarray( [[1, 2, 4] for i in xrange(20)], dtype='int32' )

# Layers
l_in = lasagne.layers.InputLayer( (N_BATCH, MAX_LENGTH), x )

l_emb = lasagne.layers.EmbeddingLayer(
  l_in,
  input_size=VOCABULARY_SIZE,
  output_size=EMBEDDING_SIZE,
  W=lasagne.init.Uniform(0.1)
)

# Output
output = lasagne.layers.get_output( l_emb, x )

# Function
train = theano.function( [x], output )

# Train
train_output = train(
  x_train_set[0: N_BATCH],
)

print 'train_output.shape: ', train_output.shape
print 'train_output: ', train_output
```

As the first form is valid for a RecurrentLayer, it seems as though it should work for an EmbeddingLayer also?

**Comment by benanne** [comment] 2015-11-06 23:09
The problem is that inputs are usually floats, so `InputLayer` assumes that the input variable type is float by default. In your case it is integer. You can override the `input_var` in the `InputLayer` constructor, but I guess that doesn't really buy you anything over specifying `x` directly in `get_output()`.

**Comment by mt-** [comment] 2015-11-09 01:07
Thanks for following up on this, I believe I'm misunderstanding something here.  Altering the example to:

```
import numpy as np
import theano
import theano.tensor as T
import lasagne


VOCABULARY_SIZE = 10
EMBEDDING_SIZE = 3
MAX_LENGTH = 6
N_BATCH = 2


# Prepare data
x_train_set = np.asarray([
  [1, 3, 2, 5, 0, 0],
  [7, 9, 3, 8, 6, 2],
], dtype='float32')

# Symbolic variables
#x = T.matrix( 'inputs' )

# Layers
l_in = lasagne.layers.InputLayer( (N_BATCH, MAX_LENGTH) )

l_emb = lasagne.layers.EmbeddingLayer(
  l_in,
  input_size=VOCABULARY_SIZE,
  output_size=EMBEDDING_SIZE,
  W=lasagne.init.Uniform(0.1)
)

y_dist = lasagne.layers.get_output( l_emb )

# Function
train = theano.function( [l_in.input_var], y_dist )

# Train
train_err = train(
  x_train_set[0:N_BATCH],
)

print 'train_err: ', train_err
```

Results in the same error.  On a similar note, using T.matrix instead of T.imatrix() results in the same error, so it appears as though the embedding layer requires that the input be of type 'int32' (as it is in the example code in the documentation).  However, having the embedding layer output an int32 results in an error when feeding the l_emb output to a RecurrentLayer() when Theano is configured to run on the gpu (floatX=float32), as seen in the following example:

```
import numpy as np
import theano
import theano.tensor as T
import lasagne


VOCABULARY_SIZE = 10
EMBEDDING_SIZE = 3
MAX_LENGTH = 6

N_BATCH = 2
N_HIDDEN = 5


# Prepare data
x_train_set = np.asarray([
  [1, 3, 2, 5, 0, 0],
  [7, 9, 3, 8, 6, 2],
], dtype=theano.config.floatX)

x_train_mask = np.asarray([
  [1, 1, 1, 1, 0, 0],
  [1, 1, 1, 1, 1, 1],
], dtype=theano.config.floatX)

# Symbolic variables
x = T.imatrix( 'inputs' )
m = T.imatrix( 'mask' )

# Layers
l_in = lasagne.layers.InputLayer( (N_BATCH, MAX_LENGTH), x )
l_mask = lasagne.layers.InputLayer( (N_BATCH, MAX_LENGTH), m )

l_emb = lasagne.layers.EmbeddingLayer(
  l_in,
  input_size=VOCABULARY_SIZE,
  output_size=EMBEDDING_SIZE,
  W=lasagne.init.Uniform(0.1)
)

l_forward = lasagne.layers.RecurrentLayer(
  l_emb,
  mask_input=l_mask,
  num_units=N_HIDDEN,
  W_in_to_hid=lasagne.init.HeUniform(),
  W_hid_to_hid=lasagne.init.HeUniform(),
  nonlinearity=lasagne.nonlinearities.tanh
)

y_dist = lasagne.layers.get_output( l_forward )

# Function
train = theano.function( [x, m], y_dist )

# Train
train_err = train(
  x_train_set[0:N_BATCH],
  x_train_mask[0:N_BATCH],
)

print 'train_err: ', train_err
```

Results in the following error:

```
Using gpu device 0: GeForce GTX 960 (CNMeM is disabled)
/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py:1019: Warning: In the strict mode, all neccessary shared variables must be passed as a part of non_sequences
  'must be passed as a part of non_sequences', Warning)
Traceback (most recent call last):
  File "embed_mask.py", line 52, in <module>
    y_dist = lasagne.layers.get_output( l_forward )
  File "/usr/local/src/Lasagne/lasagne/layers/helper.py", line 185, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/usr/local/src/Lasagne/lasagne/layers/recurrent.py", line 456, in get_output_for
    strict=True)[0]
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py", line 1044, in scan
    scan_outs = local_op(*scan_inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 509, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 526, in make_node
    inner_sitsot_out.type.dtype))
ValueError: When compiling the inner function of scan the following error has been encountered: The initial state (`outputs_info` in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 2) has dtype float32, while the result of the inner function (`fn`) has dtype float64. This can happen if the inner function of scan results in an upcast or downcast.
```

Apologies if I'm doing something wrong and the issue is with my understanding of Lasagne/Theano, I'm happy to close the issue and move the discussion to the mailing list if that's the case.  Huge thank you for looking at this.

**Comment by f0k** [comment] 2015-11-09 17:11
```python
x = T.imatrix( 'inputs' )
m = T.imatrix( 'mask' )

# Layers
l_in = lasagne.layers.InputLayer( (N_BATCH, MAX_LENGTH), x )
l_mask = lasagne.layers.InputLayer( (N_BATCH, MAX_LENGTH), m )
```
You're almost there. You fixed one issue and created another: The input to the embedding layer must be integer (so `x = T.imatrix()` is correct), but the mask will be multiplied by a float32 tensor in the recurrent layer, so if you set the mask to int as well, the result will be upcast to float64:
```
>>> import theano
Using gpu device 0: GeForce GT 640 (CNMeM is disabled)
>>> a = theano.tensor.scalar()
>>> b = theano.tensor.iscalar()
>>> a.dtype
'float32'
>>> b.dtype
'int32'
>>> (a*b).dtype
'float64'
```
Solution: Just set the mask to be a `T.matrix()`, and provide `x_train_mask` in dtype `int8` or `bool` (otherwise Theano will correctly complain that it cannot safely convert int32 to float32 without loss of precision).

**Comment by mt-** [comment] 2015-11-09 19:22
You guys rock, setting dtype='bool' on the mask solves my second issue.

Btw, in order to wrap my head around the Lasagne implementation of recurrent networks I'm porting the example detailed in this blog:

http://www.wildml.com/2015/10/recurrent-neural-network-tutorial-part-4-implementing-a-grulstm-rnn-with-python-and-theano/

over to using Lasagne.  If you'd like I'm happy to do a pull request and add it to the Lasagne examples folder (assuming it survives a check on code quality).

**Comment by f0k** [comment] 2015-11-09 19:45
> If you'd like I'm happy to do a pull request and add it to the Lasagne examples folder

The examples folder is meant to stay slim, but we've got a whole repository for more elaborate examples: [Lasagne/Recipes](https://github.com/Lasagne/Recipes). We'd welcome a pull request over there!

**Comment by f0k** [comment] 2015-11-18 15:34
Closing because there's no open question.

**Closed by f0k** 2015-11-18 15:34 UTC
