### ISSUE TITLE
Why the `bcast` is needed in `create_param()`?

### ISSUE THREAD

**Issue by david-leon** [Lasagne/Lasagne#912] opened 2018-08-02 06:21 UTC
In [`create_param()`](https://github.com/Lasagne/Lasagne/blob/a61b76fd991f84c50acdb7bea02118899b5fefe1/lasagne/utils.py#L392), these two lines confuse me:
```
        bcast = tuple(s == 1 for s in shape)
        spec = theano.shared(spec, broadcastable=bcast)
```
I'm wondering what the `bcast` is for, especially these two lines will cause theano exception `TypeError: Cannot convert Type TensorType(float32, vector) (of Variable Elemwise{add,no_inplace}.0) into Type TensorType(float32, (True,))` when `shape` arg is set to `[1]`

**Comment by nouiz** [comment] 2018-08-06 15:29
It is there to work around the fact that Theano broadcastable isn't
perfect. In fact, in some case, it is not possible to do it without user
help, but in other case, Theano could be improved too, but those case are
complicated.

**Comment by f0k** [comment] 2018-10-18 13:17
Sorry for the late reply. Lasagne has partial information on the input shapes and full information on the parameter shapes, and it uses this to set the correct broadcast patterns on Theano variables (which do not have any shape information at all). This allows some expressions using the outputs of Lasagne networks to work out of the box that would fail otherwise (see #715 for why this was introduced in the first place). On the downside, it requires extra care about broadcast patterns in user-provided variables.
Closing this issue since it was only a question, but please feel free to post how you got this error message and we can look into improving the documentation or failing earlier with a more useful message (and double-check it's not a bug in Lasagne).

**Closed by f0k** 2018-10-18 13:17 UTC
