### ISSUE TITLE
Denselayer for DBLSTM

### ISSUE THREAD

**Issue by zzw922cn** [Lasagne/Lasagne#655] opened 2016-04-03 15:38 UTC
Now I want to construct a Deep Bidirectional LSTM network,at the bottom of my network,I want to use Dense Layer,but I can't implement this ,because I find I only can use recurrent layer for the bottom.How to solve my problem?Thank you!

**Comment by f0k** [comment] 2016-06-24 15:42
Closing because this is a usage question. Please re-post on our mailing list (https://groups.google.com/forum/#!forum/lasagne-users) if the problem is still unsolved.

**Closed by f0k** 2016-06-24 15:42 UTC
