### ISSUE TITLE
Implement crop layer as in Caffe for semantic segmentation

### ISSUE THREAD

**Issue by Fengyboy** [Lasagne/Lasagne#660] opened 2016-04-14 11:39 UTC
I've been trying to implement fully convolutional networks ([fcn8s](https://github.com/shelhamer/fcn.berkeleyvision.org)), however I had some difficulty in the `crop` layer after `deconvolution`. I tried to use `SliceLayer` to perform `center`, `upper` or `lower` slicing of each axis (width and height), and the results were not satisfactory.

After checking the source of `Caffe` as [here](https://github.com/BVLC/caffe/blob/74cc4970c8f1b42056c8e36dc9944234ad663a16/python/caffe/coord_map.py), the `crop layer` takes two bottom layers (`input` and `convolution` or `deconvolution`) and outputs a single layer that matches the output shape of `input`. In addition, it performs differently for `convolution` and `deconvolution` based on their parameters, e.g., `kernel size`, `stride` and `pad`.

Can anyone give some suggestions on how to implement this in Lasagne/Theano? Many thanks in advance.

**Comment by f0k** [comment] 2016-04-14 12:55
Do the cropping options of the [ElemwiseMergeLayer](http://lasagne.readthedocs.org/en/latest/modules/layers/merge.html#lasagne.layers.ElemwiseMergeLayer) help? If so, you could call it with `MergeLayer([input, deconv], merge_function=lambda input, deconv: deconv, cropping=...)`.
Just noticed that the `autocrop()` function describing the cropping argument is missing from the docs, its docstring can be found in the source for now: https://github.com/Lasagne/Lasagne/blob/9fab702/lasagne/layers/merge.py#L16

In future, please direct usage questions to the mailing list: https://groups.google.com/forum/#!forum/lasagne-users
Thank you! (I'm closing this issue because it's not a bug report or feature request, but feel free to comment if the question is not resolved, or re-post on the mailing list.)

**Closed by f0k** 2016-04-14 12:55 UTC

**Comment by Fengyboy** [comment] 2016-04-14 13:30
Thanks for the quick reply. I've reposted on the mailing list: https://groups.google.com/forum/#!topic/lasagne-users/KRERjzCaI3Y.
