### ISSUE TITLE
[Bug Report] in class DropoutLayer

### ISSUE THREAD

**Issue by lc82111** [Lasagne/Lasagne#330] opened 2015-07-16 07:43 UTC
```
class DropoutLayer(Layer):
         def get_output_for(self, input, deterministic=False, **kwargs):
               input_shape = self.input_shape
```
It's not safe to get input_shape from self.input_shape (input_shape = self.input_shape), when you define the input to propagate through the network instead of using the input variable associated with the network's input layer.

To illustrate my point, assuming I defined my DropoutLayer with code:
```
myDenselayer = DenseLayer(InputLayer((2,2)) # shape= 2 x 2
myDropoutlayer = DropoutLayer(myDenselayer)
```
If, I invoked the above with:
```
myInput = T.matrix() # shape= 3 x 3
helper.get_output(myDropoutlayer, myInput)
```
In above context, self.input_shape (2 x 2) have a  different value from myInput's shape (3 x 3).

**Comment by f0k** [comment] 2015-07-16 10:00
If you set the `InputLayer` to shape `(2, 2)`, you must not pass input of a different shape to the network. If you don't want to fix the shape at compile time, set the dimension sizes you want to vary to `None`: `InputLayer((None, None))`. The `DropoutLayer` will use the run-time shape instead of a fixed shape then (which is a little bit less efficient because Theano doesn't know the number of required random streams then).

We tried to document this for the `InputLayer`: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/input.py#L16-L69
The explanation specifically mentions the batch size, but it applies to all dimensions. Is there anything we can change in the documentation (of this layer, or elsewhere) to make it clearer?

(Closing this issue because it is not a bug, but I'd still be interested in feedback on the documentation!)

**Closed by f0k** 2015-07-16 10:00 UTC
