### ISSUE TITLE
CNN issues in mnist exmaple (Conv2DLayer)

### ISSUE THREAD

**Issue by DeeShoaib** [Lasagne/Lasagne#642] opened 2016-03-19 00:20 UTC
Hello there, I am  stuck in CNN for almost two days.
I have found there are some problems with  Conv2DLayer. When I comment out all the conv2D layer code in mnist.py example, everything work fines; but when I uncomment them again my terminal doesn't  train or test. It show this message infinite times untill I press Ctrl+C.
 ** On entry to SGEMM  parameter number  3 had an illegal value
 ** On entry to SGEMM  parameter number  3 had an illegal value
 ** On entry to SGEMM  parameter number  3 had an illegal value............
............................... 
All other layers are working great..
My installed lasagne version is 0.2.dev1 and theano version is 0.8.0rc1.

Please let me know if I am making some mistakes and suggest me the solution.
I Would really appreciate the help..Thanks

**Comment by benanne** [comment] 2016-03-19 10:43
This definitely shouldn't happen with the unmodified example code, have you tried upgrading Theano to the latest version from GitHub? It also sounds like this is a Theano issue, so you may have better luck reporting it there.

**Comment by f0k** [comment] 2016-03-21 12:29
Parameter 3 is one of the matrix sizes (http://www.math.utah.edu/software/lapack/lapack-blas/sgemm.html). Which BLAS library do you have installed? What platform do you run on (Windows/Linux/Mac, which version)?

**Comment by f0k** [comment] 2016-06-24 15:45
Closing because there is no more feedback from the OP. Please comment again if the problem is still unsolved, and post a minimal code example to trigger the problem. If anything, it's probably a Theano bug, but we'd still be interested in fixing this if it is.

**Closed by f0k** 2016-06-24 15:45 UTC

**Comment by Sophia-lrr** [comment] 2017-01-08 10:29
I have encountered the same question, have you solved this problem? Thank you~~

**Comment by f0k** [comment] 2017-01-28 13:15
> I have encountered the same question, have you solved this problem?

Did you try updating Theano to the bleeding-edge version (http://lasagne.readthedocs.io/en/latest/user/installation.html#bleeding-edge-version)? Otherwise, which BLAS library do you have installed, and which platform do you run on (Windows/Linux/Mac, which version)?
